version: '3'
services:
  app:
    container_name: ay-design-library-app
    tty: true
    stdin_open: true
    build:
      context: .
      args:
        - AZURE_REGISTRY_USERNAME=${AZURE_REGISTRY_USERNAME}
        - AZURE_REGISTRY_PASSWORD=${AZURE_REGISTRY_PASSWORD}
    volumes:
      - .:/share
    env_file:
      - .env
    ports:
      - "6060:6060"
