# Tests pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    sh scripts/writeAzureRegistry.sh
  displayName: 'Set up NPM'

- script: |
    npm ci
    if [ $? -ne 0 ]; then
      exit 1
    fi
  displayName: 'Install dependencies'

- script: |
    npm run lint
    if [ $? -ne 0 ]; then
      exit 1
    fi
  displayName: 'Execute linters'

- script: |
    npm run test:ci
    if [ $? -ne 0 ]; then
      exit 1
    fi
  displayName: 'Execute Tests'

- script: |
    npm run prod:build
    if [ $? -ne 0 ]; then
      exit 1
    fi
  displayName: 'Build the project'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    mergeTestResults: true
    testRunTitle: 'Publish result'
