name: Lint and test

on:
  push:
    branches: '*/*'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: authenticate npm
      run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.PACKAGING_TOKEN }}

    - run: git config --global user.name ${{ secrets.RELEASE_USERNAME }}
    - run: git config --global user.email ${{ secrets.RELEASE_EMAIL }}

    - name: installing npm
      run: npm install

    - name: lint
      run: npm run lint

    - name: test
      run: npm test