name: CI

on:
  push:
    branches:
      - 'feature/**'
      - 'update/**'
      - 'fix/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci

      - name: Build library
        run: npm run build

      - name: Build storybook
        run: npm run build:storybook
