name: Library release

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: authenticate with Github
      run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.PACKAGING_TOKEN }}

    - run: git config --global user.name ${{ secrets.RELEASE_USERNAME }}
    - run: git config --global user.email ${{ secrets.RELEASE_EMAIL }}

    - name: installing packages
      run: yarn install

    - name: lint
      run: yarn run lint

    - name: test
      run: yarn test

    - name: build
      run: yarn run build-package

    - name: clear env
      run: git reset --hard

    - name: release
      run: yarn run release