name: Library release

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: installing npm
      run: npm install

    - name: installing npm
      run: npm install

    - name: lint
      run: npm run lint

    - name: test
      run: npm test

    - name: build
      run: npm run build-package

    - name: release
      run: npm run release